---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: monostream/nodejs-gulp-bower
    tag: 'latest'

inputs:
- name: pipeline
- name: project
- name: version

outputs:
- name: build-output

params:
  TERM: dumb
  ARTIFACT_ID: simple-ui

run:
  path: pipeline/ci/build.sh
